services:
  postgres:
    image: postgres:16
    container_name: golive-postgres
    restart: always
    environment:
      POSTGRES_DB: golive_db
      POSTGRES_USER: golive_user
      POSTGRES_PASSWORD: golive_password
    ports:
      - "5432:5432"
    volumes:
      - golive_postgres_data:/var/lib/postgresql/data

  livekit:
    image: livekit/livekit-server
    container_name: golive-livekit
    command: --dev
    environment:
      LIVEKIT_KEYS: "devkey: secret"
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"

volumes:
  golive_postgres_data: