package com.golivebackend.stream.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

/**
 * Records that a specific session liked a specific stream.
 *
 * The unique constraint on (session_id, stream_id) enforces
 * one like per session per stream at the database level.
 * No application-level check can be bypassed — the DB is
 * the final enforcer.
 *
 * sessionId is generated by the frontend (UUID stored in localStorage).
 * We never validate it — we trust it as an anonymous session token.
 */
@Entity
@Table(
        name = "stream_likes",
        uniqueConstraints = @UniqueConstraint(
                name = "uq_session_stream_like",
                columnNames = {"session_id", "stream_id"}
        )
)
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StreamLike {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "like_id", updatable = false, nullable = false)
    private UUID likeId;

    @Column(name = "session_id", nullable = false)
    private String sessionId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stream_id", nullable = false)
    private Stream stream;

    @Column(name = "created_at", nullable = false, updatable = false,
            columnDefinition = "TIMESTAMPTZ")
    private Instant createdAt;
}